### ISSUE TITLE
Equality Explorer - master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#1]
## Design
- [x] **Sim folder and design doc created** (Date: 08/15/2016) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 09/06/2016)
- [x] **Design concept complete**  (Date: 09/26/2016)
- [x] **Wireframes complete** (Date: 01/27/2017) 
- [x] **Mockups complete** (Date: 06/15/2017) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** (skipped, see #31)
- [x] **Interviews complete** (Date: 5/25/18) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //) 
  - [x] Performance acceptable - see #83
  - [x] Carefully review `?showPointerAreas` - see issue #68
  - [x] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [ ] Sim primer draft
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [x] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 04/27/2017)
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 05/01/2017)
- [x] **Sim is "feature complete"** (Date: 5/1/2018) 
- [x] **Code review completed** (Date: 6/18/18), see #123
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped) - see #125
  - [x] Verify credits - see issue #2
- [x] **Published** (Date: 7/18/18) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [x] **Dev testing started** (Date: 6/18/18) - see https://github.com/phetsims/QA/issues/131 
- [x] **Dev testing completed** (Date: 7/5/18) 
- [x] **First RC published** (Date: 7/13/18)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbmtLWDVBOS1DWWc)
- [x] **RC testing completed** (Date: 7/17/18)

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed**
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ files
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing completed** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by ariel-phet** [comment]
## Design
- [ ] **Sim folder and design doc created** (Date: //) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed**
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Add an activity
  - [ ] Sim primer draft
  - [ ] Verify credits
- [ ] **Post-publication items** 
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (such as QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to chipper/data/ files
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Published** (Date: //) 
  - [ ] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing completed** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)

**Comment by ghost** [comment]
Links to Matrices:

1. EqEx: https://docs.google.com/spreadsheets/d/1-wXbbXEuK1M8-8zOoBZJjgGkWohWb57q3fwOtFFNeMI/edit#gid=2
2. EqEx Basics: https://docs.google.com/spreadsheets/d/1OA3O2j8Ruek4ELKLpYrMpKI6XVXB9qMDjO_Gt2YZFnU/edit#gid=2
3. EqEx Two Variables: https://docs.google.com/spreadsheets/d/1hoCfDa2wdUbZMwcjFbCflj0UfG1AKF5A3PWm3pUVxE4/edit#gid=2

**Comment by pixelzoom** [comment]
All remaining items in the checklist are for @amanda-phet to complete.

**Comment by amanda-phet** [comment]
@ariel-phet can you please add to Gooru and Edmodo?

**Comment by pixelzoom** [comment]
@ariel-phet see https://github.com/phetsims/equality-explorer/issues/1#issuecomment-407917529. Have you added this sim to Gooru and Edmodo?

**Comment by pixelzoom** [comment]
Remaining checklist items are covered by #145, #146 and #147. 

Closing.
