### ISSUE TITLE
requirements for "locked" feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#19]
As I'm beginning to implement the "couplers" feature, I have many questions that are not answered by the [design document](https://docs.google.com/document/d/1xu9nawWcndFqgg5zyCGm25h-OFUsuFYnXF3QHW42spQ/edit).   So I'm creating this issue, which can be referred to in the design document.  

I'll number each of my questions (so they can be referred to in comments) and make them checklist items (so they can be checked off when completed). 

Some of these issues will be related to the "sum to zero" feature, whose requirements appear in https://github.com/phetsims/equality-explorer/issues/17.

**Comment by pixelzoom** [comment]
- [x] (1) What is the terminology for this feature? There's been various terminology floating around (coupled, linked, locked, dragged item, ghost item, equivalent item, ...) and that's problematic for clarity of code and GitHub issues.
**DECISION**: locked, dragged item, ghost item, inverse item, zero pair

- [x] (2) Multi-touch: What happens when coupling is turned ON while we're in the process of dragging an item?  Example: coupling is off, drag 1 out of left panel, turn on coupling - does drag of 1 continue as if coupling is off? does a 1 ghost suddenly appear?
**DECISION**: ghost immediately appears

- [x] (3) Multi-touch: What happens when coupling is turned OFF while we're in the process of dragging an item? Example: coupling is on, drag 1 out of left panel, ghost 1 comes out of right panel, turn coupling off - what happens to ghost 1? does it continue to exist? disappear? fly back to right panel?
**DECISION**: ghost immediately disappears

- [x] (4) Multi-touch, Solving screen: What happens when a universal operation is applied while we're in the middle of a drag that caused a new item to appear on a plate. Example: 1 on left plate, nothing on right plate, start dragging 1, -1 appears on right plate, apply a universal operation, return 1 to left plate, describe what happens to the -1 on the right plate.
**DECISION**: universal operation is applied to everything on the plate

- [x] (5) Does the sum-to-zero feature work while coupling is turned on? If so, there are many related questions (see below).
**DECISION**: yes

- [x] (6) What happens to ghost item when dragged item sums to zero? Example: Suppose I'm dragging 1 to the left plate, and a ghost 1 is tracking it to the right plate. If I drop the dragged 1 on a -1 (summing them to zero), what happens to the ghost 1? Does it just disappear? Animate back to its panel?...
**DECISION**: the ghost 1 would remain on the right plate

- [x] (7) Does the ghost item interact interact with inverse items? (I think not.) If the dragged item is dropped such that the ghost item overlaps its inverse, does the ghost item sum with its inverse (I think not, that wouldn't be coupled) or simply animate to the closest cell? (I think yes.)
**DECISION**: it would animate to the closest cell

- [x] (8) Suppose I have 1 on the left plate, nothing on the right plate. Dragging the 1 off the left plate should create a -1 on the right plate, and a ghost 1 that tracks the dragged 1. If the dragged 1 is released above the left plate (so that it returns to that plate), should the ghost 1 "sum to zero" with the -1 on the right plate? Or should the right 1 and -1 simply disappear?
**DECISION**: the right 1 and -1 simply disappear

- [x] (9) Items have a shadow while dragging. Do ghost items also have a shadow?
**DECISION**: yes, shadow means "not on plate"

- [x] (10) Multi-touch: When dragging an item off the scale results in an item being created on the scale, is that item interactive?  Example: 1 on left plate, nothing on right plate, start dragging 1, -1 appears on right plate, is the -1 interactive? (I hope not.) If not interactive, is there any visual cue needed?
**DECISION**: yes, the item created on the plate in interactive. The ghost 1 and -1 on the plate are a "zero pair". If the dragged 1 is dropped above the scale, ghost will animate to the location of the -1, and they will both disappear. The -1 (part of the zero pair) is draggable, but if dragged the "zero pair" relationship is broken.

- [x] (11) Is the ghost item ever interactive?  While dragging an item, can its ghost item be grabbed? (I think not.) After dragged item, is released, can its ghost item be grabbed? (I think not.)
**DECISION**: A ghost item is not interactive. An in-motion ghost item can not be grabbed.

**Comment by pixelzoom** [comment]
Some decisions that were made in previous discussions, most of which don't appear in the design document. @amanda-phet please review these to make sure that I have them correct.

- [x] (12) How does the ghost item move relative to the dragged item?
**DECISION**: While dragging an item, the ghost item moves y-proportionally below the plate. Above the plate it tracks exactly. x-axis movement is tracked exactly.  After dragged item is released, animation occurs such that dragged item and ghost item are added to their plates at exactly the same time.

- [x] (13) How do we choose the ghost item to remove from the plate?
**DECISION**: Choose the ghost item that is closest to the cell that the dragged item was removed from.

- [x] (14) How do we choose where the ghost item goes on the scale?
**DECISON**: When dragged item is released, ghost item animates to closest empty cell on its plate.

- [x] (15) What happens if removing an item from a plate would result in creating an item on the other plate, but there's no room on the other plate?  
**DECISION** 9/27/17: Show a dialog with message "[Left/Right] side of the balance is full". (This scenario should be rare, so not worth the cost to implement more complicated options.)

- [x] (16) Can I drag an item out of a panel when the plate for the ghost item is full?
**DECISION**: Yes.  When the dragged item is released, both the dragged item and ghost item will animate back to their respective panels.

- [x] (17) Multi-touch: What happens if the plate becomes full before or after the dragged item is released? 
**DECISION**: The dragged item and ghost item animate back to their respective panels.

(EDIT: @amanda-phet and I reviewed these in 11/28/17 design meeting. They all look correct.)

**Comment by pixelzoom** [comment]
- [16] Multi-touch: What happens if the plate becomes full after the dragged item is released? This can occur with either the dragged item's plate or the ghost item's plate.  Example: left plate empty, right plate has one empty space, drag 1 to left plate, 1 ghost follows, drag another 1 to right plate to make the plate full, related the dragged 1 - what happens to the dragged 1 and ghost 1, now that the right plate is full?

**Comment by amanda-phet** [comment]
(1) The design doc uses linked and unlinked in the terminology section, but when we switched from a coupler to a lock, I believe locked and unlocked started getting used interchangeably. Reading below, it seems you are using coupling on and coupling off. If that is easier for you we can use that terminology instead, but since there are no couplers anymore I think we should use different terms. I’m not sure what the confusion is about the terms for dragged item and ghost item. Let’s discuss and I can update the terminology section of the design doc to reflect a final decision. 

(2) - (3) This is pretty complicated, so I’m not sure I have a great answer yet. Since a ghost object is special (not interactive), I think we could have a ghost suddenly appear/disappear in these scenarios. Suppose you drag a 1 out of the left panel and toggle the lock… a ghost would flicker on and off on the right side. 

(4) The universal operation can be applied while the 1 is off the plate, and it just doesn’t get applied to the 1. It’s a weird scenario, but nothing mathematically fishy would happen. Suppose the left is 2x+1 and the right is x. If I remove 1 from the left the balance now says 2x and x-1. If I +/- a number it just gets added to or subtracted from the constant term. If I •/÷ a number it gets applied to all terms. And if I return the 1, a 1 gets added to both the left and right sides. 

(5) yes

(6) the ghost 1 would remain on the right plate. 

(7) it would animate to the closest cell.

(8) the 1 and -1 disappear.

(9) The shadow is meant to indicate that an item is *not* on a plate, so any item in motion should have a shadow. 

(10) A *ghost item* is never interactive, but in your example I’m not sure why the -1 wouldn’t be interactive. 

(11) Correct x2. A ghost item is not interactive. An in-motion ghost item can not be grabbed. 

(12) correct

(13) correct

(14) correct

(15) correct

(16) correct

(17) correct

(@pixelzoom EDIT: these answers were propagated up to **DECISION**s in https://github.com/phetsims/equality-explorer/issues/19#issuecomment-344364170.)

**Comment by pixelzoom** [comment]
@amanda-phet and I are going to meet about this issue today. 

@amanda-phet I don't understand (6) and (8), and it sounds like you don't understand the implications of (10). So we'll need to discuss those.

**Comment by pixelzoom** [comment]
@amanda-phet and I are going to meet about this issue today, specifically:

- [x] (1) decide on consistent terminology, apply to design doc
**DECISION**: locked, dragged item, ghost item, inverse item, zero pair

- [x] I don't understand reply to (6) in https://github.com/phetsims/equality-explorer/issues/19#issuecomment-346461741
Got it, as described.

- [x] I don't understand reply to (8) in https://github.com/phetsims/equality-explorer/issues/19#issuecomment-346461741
Got it, as described.

- [x] Discuss the implications of (10), especially in light of the answer to (8).
**DECISION**:  In my scenario, the ghost 1 and -1 on the plate are a "zero pair".   If the dragged 1 is dropped above the scale, ghost will animate to the location of the -1, and they will both disappear. The -1 (part of the zero pair) is draggable, but if dragged the "zero pair" relationship is broken.    

(EDIT: these **DECISION**s were propagated up to https://github.com/phetsims/equality-explorer/issues/19#issuecomment-344364170.)

**Comment by pixelzoom** [comment]
@amanda-phet and I talked about how ~80% of the code is likely to be written to handle multi-touch scenarios that are unlikely to ever happen.  (For example, animation having to adapt to its target cell being filled.)  To handle these cases, it might be easier (and less costly) to simply make the sim go immediately to the "end state" -- eg, items move immediately to locations, instead of animating. @amanda-phet said this sounds good, I'll investigate.

**Comment by pixelzoom** [comment]
I'm working on the Solving screen (and Mystery screen?) before this feature. So unassigning for now, until I resume working on it.

**Comment by pixelzoom** [comment]
Solving screen is completed, with the exception of the lock feature.  Self-assigning this issue, since the lock feature is the next thing to implement.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/equality-explorer/issues/19#issuecomment-347629182, the proposal to make simplifications for multi-touch scenarios:   

One such simplification related to this feature was proposed at a recent design meeting. I can't recall for sure who raised it, but my handwritten notes suggest @ariel-phet.  The suggestion was to ignore changes to the lock control once a drag is in progress, instead of having to adapt to lock changes while dragging. This would greatly simplify implementation and testing, because it would cut the number of scenarios related to this feature roughly in half (so WAG 50% savings).  It would also eliminate potential issues with responsiveness -- we generally try to avoid doing complex things during a drag cycle.

I discussed this simplification with @amanda-phet via Slack today. In summary, she was not in favor it, and said "I definitely prefer the original scenario. I think it just makes more sense." So I will proceed with full multi-touch support.

**Comment by pixelzoom** [comment]
Summary of some multi-touch scenarios that I discussed with @amanda-phet on slack. We hadn't considered these previously. 

For terms taken off the scale:

(a) Start with 'x' on left, 'x' on right, lock off.  Take 'x' off left, turn lock on.  A new 'x' ghost is created, not taken from the right.

(b) Start with 'x' on left, 'x' on right, lock on.  Take 'x' off left, which also removes 'x' ghost from right.  Turn lock off, 'x' on right falls back to right plate.  Turn lock on and (as above) a new 'x' ghost is created, not taken from the right.

We also hadn't discussed terms that have been released and are in the process of animating (to plate or toolbox).  If the lock is turned on, a new ghost needs to be created for each animating term.  If the lock is turned off, the animating term's ghost needs to be deleted.  

Yikes. Very complicated, and difficult to describe.

**Comment by pixelzoom** [comment]
@amanda-phet and I discussed another simplification via Slack.  Summary:

When the state of the lock is changed, delete all terms that are not on the scale.  This includes all terms that are dragging or animating.   This is easy to describe, and is arguably preferable to some of the complicated/weird multi-touch scenarios that we would otherwise need to support.

We both think this may be a winner, and I'm going to proceed down this path.

**Comment by pixelzoom** [comment]
Re the simplification in the previous comment... Deleting all terms that are _not_ on the scale when the lock state is changed required 4 lines of new code and 15 minutes to implement and test (see previous commit).  And bonus -- it's totally independent of the dragging and animation code. That's a _huge_ implementation savings over what we had previously discussed doing.

**Comment by pixelzoom** [comment]
Labeling with high priority, since this sim is supposed to be "feature complete" by March 26.

**Comment by pixelzoom** [comment]
An additional simplification will be made, see #73.  

Slack discussion:

Chris Malley [11:42 AM]
I’d like to propose an additional EqEx simplification to eliminate some weird corner cases with the lock feature.  When any of the following actions are performed, all terms that are dragging or animating (ie, not on the scale) will be deleted:  (1) organize button is pressed, (2) ‘reset scale’ button is pressed, (3) snapshot is restored.  These are all consistent with what happens when you change the lock.  Are these acceptable simplifications?

Amanda McGarry [11:51 AM]
Those make sense to me!

**Comment by pixelzoom** [comment]
@amanda-phet EqEx lock question.  Suppose I have ‘x’ on left plate, nothing on right plate, lock is on.  I drag ‘x’, which creates ‘x’ (ghost) and ‘-x’ (inverse) on the right plate.  While dragging, I turn the lock off.  Are all 3 terms (dragged, ghost, inverse) deleted, or does -x (inverse) remain on the right plate?

DECISION: All 3 terms are deleted.

**Comment by pixelzoom** [comment]
Another simplification for EqEx:  While a term is animating (to the toolbox or scale) it cannot be grabbed.  Once you release it, you can’t grab it again until it lands on the scale.  This will disappoint @phet-steele (and disappoints me a tiny bit), but will not be an issue in practice — things move so quickly that there is no reason to support grabbing a term while it’s animating.   And not having to support that simplifies things a bit when the lock is on.  @amanda-phet please tell me ASAP if you disagree.

DECISION: OK.

**Comment by pixelzoom** [comment]
A note about the lock and snapshots, from Slack discussion with @amanda-phet:

Chris Malley [3:17 PM]
An interaction that I’ve notice between the lock and snapshots feature… When you take a snapshot, it does not include the state of the lock.  So (for example) you may take a snapshot with the lock off, then restore the snapshot later when the lock is on.   That’s probably fine, but I wanted to make sure you were aware of it.

Amanda McGarry [4:12 PM]
Thanks. I agree it is fine. The lock affects dynamic interactions, not the state of equality, so I am not concerned about it.

**Comment by pixelzoom** [comment]
Email that I sent to the design team, reproduced here because it contains terminology and things that need followup (check list items).

---

Team,

Here’s the first version of the lock feature:

https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.112/phet/equality-explorer_en_phet.html

Some terminology, so we can communicate about this feature:

• The dragged term is the term that you’re dragging. 
• The equivalent term (formerly “ghost” term) is the term on the opposite side that follows along with the dragged term. It has the same value as the dragged term. For example, if you’re dragging 2x, the equivalent term will also be 2x.
• The inverse term is the term that gets create on the opposite plate if no equivalent term is already on the plate. It’s value is the inverse of the equivalent term.  For example, if the equivalent term is 2x, the inverse term is -2x.  (Inverse term is only relevant for the Numbers and Variables screens. In Operations, the equivalent term is subtracted from what’s on the plate.)
• The opposite plate is the plate associated with the equivalent term, opposite the dragging term.

First, a bit about the current implementation of the lock feature. It's big, fragile, complicated, unmaintainable. It needs at least another iteration, more likely two. Change requests will never be quick or easy. That said...

Known problems, on my list to fix:

- [x] It’s possible to exceed the number limit (1E9) for the opposite plate. 
- [x] There are occasional layering issues with the equivalent term — it gets behind other terms. (5/5/18 fixed)
- [x] With lock on, "sum to zero" animation occurs in the wrong place for dragged term (Numbers, Variables, Operations). (5/6/18 fixed)
- [x] In the Operations screen, there is no “sum to zero” animation when the equivalent term and what’s on the plate sum to zero. (5/6/18 fixed)

Design issues, which I intended to first discuss with Amanda (but feel free to provide your 2 cents):

- [x] The equivalent term currently tracks the dragged term while dragging and while animating.  Both terms must be added to the scale simultaneously. When the dragged term reaches its final location, the equivalent term pops to its final location. This approach was easiest, looks pretty good, and may be sufficient. Proportional animation (where dragged and equivalent terms move at different speeds) will add an additional layer of complexity to something that is already way too complex. (5/3/18 design meeting: good as is. Clearly communicates "locked".)

- [x] What is the desired algorithm for choosing an equivalent term on the opposite plate? The current implementation finds the term that is closest to the same cell that the dragged term occupied.  For example, if the dragged term was taken from the bottom-left cell on the left plate, then an equivalent term will be located that is closest to the bottom-left cell on the right plate.
(5/3/18 design meeting: good as is.)

- [x] What is the desired algorithm for choosing an empty cell for the equivalent term? The current implementation finds the cell that is closest to the same cell occupied by the dragged term.  For example, if the dragged cell was put in the bottom-left cell on the left plate, then the equivalent term will be put in a cell that is closest to the bottom-left cell on the right plate.
(5/3/18 design meeting: good as is.)

QA issues (for which we’re *really* going to miss Steele):

- [x] There are a *minimum* of 30 unique scenarios that must be tested. They will need to be documented for QA.  See issue #87.
• It’s going to take a long time to test just this feature, and it’s highly likely that something will be missed.

Whew.

**Comment by pixelzoom** [comment]
5/3/18 design meeting notes:

Discussed issues in https://github.com/phetsims/equality-explorer/issues/19#issuecomment-385856336, decisions as noted in that comment.

**Comment by pixelzoom** [comment]
All issues noted in https://github.com/phetsims/equality-explorer/issues/19#issuecomment-385856336 have been addressed.

I need to do more testing (particularly multi-touch) before I declare this ready for interviews.

**Comment by pixelzoom** [comment]
This feature has now received sufficient testing to close this issue.  Any related problems will be (and have been) tracked in new GitHub issues.
